In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
documents=[
    'i love burger ',
    'burger is the best',
    'he likes pizza',
    'pizza is the best'
]
vectorizer=CountVectorizer(ngram_range=(3,3))
X=vectorizer.fit_transform(documents)
print('Vocabulary',vectorizer.get_feature_names_out())
print('BoW Matrix',X.toarray())

Vocabulary ['burger is the' 'he likes pizza' 'is the best' 'pizza is the']
BoW Matrix [[0 0 0 0]
 [1 0 1 0]
 [0 1 0 0]
 [0 0 1 1]]
